version: "3.7"
services:
    app:
        build:
            args:
                user: adi
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel:1.0.0
        container_name: toko-online
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-networks

    db:
        image: mysql:8.0
        container_name: toko-online-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - laravel-networks

    nginx:
        image: nginx:alpine
        container_name: toko-online-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel-networks

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: toko-online-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 9001:80
        networks:
            - laravel-networks

networks:
    laravel-networks:
        driver: bridge
